<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Lead Id Form</title>

    <style>
        .headers {
            font-weight: bold;
        }

        .custom-row {
            margin-left: 10px;
            border-radius: 10pc;
            /* Adjust the left margin as needed */
        }

        body {

            background-color: #adcbd7;

            /* Hide vertical scrollbar */
        }

        .headings {

            margin-top: 10px;
            background-color: #483D8B;
            text-align-last: center;
        }

        .textColors {
            color: white;
        }
    </style>
    <script>
        window.history.replaceState({}, document.title, window.location.pathname);
    </script>

</head>

<body>

    @extends('layouts.avataradmin')



    <!-- container box starts here  -->


    @section('content')



        <div class="container">
            <div class="custom-row">
                <div class="col-md-10">
                    <div class="card">
                        <div class="headings">
                            @if($centerMatch == 'J.Sons Communication')
                                <h3 class="textColors">J.Sons Xfer Form</h3>
                            @elseif($centerMatch == 'Sellerz BPO')
                                <h3 class="textColors">Sellerz Xfer Form</h3>
                            @else
                                <h3 class="textColors">Xfer Form</h3>
                            @endif
                        </div>


                        @if(!empty($recording_filename) && !empty($recording_id))
                            <form id="lead-form" method="POST" action="/avatarleads-store"
                                class="needs-validation">
                                <!-- CSRF Token -->
                                @csrf
                                <div class="card-body">
                                    <div class="row">
                                        <!-- First column -->
                                        <div class="col-md-4">


                                            <div class="form-group">
                                                <label for="company_name *" class="form-label headers">Lead ID</label>
                                                <input class="form-control font-style" readonly id="lead_id" name="lead_id"
                                                    placeholder="Lead ID" value="{{$lead_id}}">
                                            </div>
                                            <div class="form-group">
                                                <label for="Smoker" class="form-label headers">Smoker</label>
                                                <select type="text" name="Smoker" class="form-control custom-select" id="Smoker"
                                                    required>
                                                    <option disabled selected value="">Select</option>
                                                    <option value="Yes">Yes</option>
                                                    <option value="No">No</option>
                                                </select>
                                            </div>

                                    <div class="form-group">
                                        <label for="centername" class="form-label headers">Center</label>
                                        <input class="form-control" readonly id="centername" name="centername" value="{{$centerMatch }}">
                                        <div class="form-group">
                                            <label hidden for="recording_link">Recording Link:</label>
                                            <!-- Recording link will be generated by controller from dialers_unified table -->
                                            <input type="text" hidden name="recording_link" id="recording_link" class="form-control" value="">
                                            <input type="text" hidden name="recording" id="recording" class="form-control" value="http://{{$server_ip}}/RECORDINGS/MP3/{{$recording_filename}}-all.mp3">
                                        </div>
                                    </div>

                                        </div>
                                        <!-- Second column -->
                                        <div class="col-md-4">


                                            <div class="form-group">
                                                <label for="agent_name" class="form-label headers">Agent Name</label>
                                                <input class="form-control font-style" readonly id="agent_name"
                                                    name="agent_name" placeholder="Agent Name" value="{{$fullname}}">
                                            </div>
                                            <div class="form-group">
                                                <label for="AGE" class="form-label headers">Age</label>
                                                <select class="form-control custom-select" name="AGE" id="AGE" required>
                                                    <option disabled selected value="">Select</option>
                                                    @for($i = 18; $i <= 100; $i++)
                                                        <option value="{{ $i }}">{{ $i }}</option>
                                                    @endfor
                                                </select>
                                            </div>


                                            <div class="form-group">
                                                <label for="dialername" class="form-label headers">Dialer</label>
                                                <input class="form-control font-style" readonly id="dialername"
                                                    name="dialername" placeholder="dialername" value="{{ $dialerMatch }}">
                                            </div>

                                        </div>

                                        <!-- third column -->
                                        <div class="col-md-4">

                                            <div class="form-group">
                                                <label for="dialer_id" class="form-label headers">Dialer Id</label>
                                                <input class="form-control" readonly id="dialer_id" name="dialer_id"
                                                    value="{{$closer}}">
                                            </div>
                                            <div class="form-group">
                                                <label for="closer_name" class="form-label headers">Closer</label>
                                                <select name="closer_name" class="form-control custom-select" id="closer_name"
                                                    required>
                                                    <option disabled selected value="">Select Closer</option>
                                                    @foreach($verifiers as $verifier)
                                                        <option value="{{ $verifier->id }}">{{ $verifier->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                                <div class="card-footer text-end">
                                    <div class="form-group">
                                        <!-- Submit button -->
                                        <input class="btn btn-print-invoice btn-primary m-r-8" type="submit" value="Submit"
                                            onclick="showSuccessMessage()">
                                    </div>

                                    <input type="hidden" name="list_id" id="list_id" class="hidden" value="{{ $list_id }}">
                                    <input type="hidden" name="phone_number" class="hidden" value="{{ $phone_number }}">
                                    <input type="hidden" name="campaign" class="hidden" value="{{ $campaign }}">
                                    <input type="hidden" name="lead_id" class="hidden" value="{{ $lead_id }}">
                                    <input type="hidden" name="closer" class="hidden" value="{{ $closer }}">
                                    <input type="hidden" name="recording_filename" class="hidden"
                                        value="{{ $recording_filename }}">
                                    <input type="hidden" name="recording_id" class="hidden" value="{{ $recording_id }}">

                                    <!-- <input type="hidden" name="fullname" class="hidden" value="{{ $fullname }}"> -->
                                    <input type="hidden" name="vendor_id" class="hidden" value="{{ $vendor_id }}">
                                    <input type="hidden" name="gmt_offset_now" class="hidden" value="{{ $gmt_offset_now }}">
                                    <input type="hidden" name="phone_code" class="hidden" value="{{ $phone_code }}">
                                    <input type="hidden" name="title" class="hidden" value="{{ $title }}">
                                    <input type="hidden" name="first_name" class="hidden" value="{{ $first_name }}">
                                    <input type="hidden" name="middle_initial" class="hidden" value="{{ $middle_initial }}">
                                    <input type="hidden" name="last_name" class="hidden" value="{{ $last_name }}">
                                    <input type="hidden" name="address1" class="hidden" value="{{ $address1 }}">
                                    <input type="hidden" name="address2" class="hidden" value="{{ $address2 }}">
                                    <input type="hidden" name="address3" class="hidden" value="{{ $address3 }}">
                                    <input type="hidden" name="city" class="hidden" value="{{ $city }}">
                                    <input type="hidden" name="state" class="hidden" value="{{ $state }}">
                                    <input type="hidden" name="province" class="hidden" value="{{ $province }}">
                                    <input type="hidden" name="postal_code" class="hidden" value="{{ $postal_code }}">
                                    <input type="hidden" name="country_code" class="hidden" value="{{ $country_code }}">
                                    <input type="hidden" name="gender" class="hidden" value="{{ $gender }}">
                                    <input type="hidden" name="date_of_birth" class="hidden" value="{{ $date_of_birth }}">
                                    <input type="hidden" name="alt_phone" class="hidden" value="{{ $alt_phone }}">
                                    <input type="hidden" name="email" class="hidden" value="{{ $email }}">
                                    <input type="hidden" name="security_phrase" class="hidden" value="{{ $security_phrase }}">
                                    <input type="hidden" name="comments" class="hidden" value="{{ $comments }}">
                                    <input type="hidden" name="user" class="hidden" value="{{ $user }}">
                                    <input type="hidden" name="pass" class="hidden" value="{{ $pass }}">
                                    <input type="hidden" name="orig_pass" class="hidden" value="{{ $orig_pass }}">
                                    <input type="hidden" name="phone_login" class="hidden" value="{{ $phone_login }}">
                                    <input type="hidden" name="original_phone_login" class="hidden"
                                        value="{{ $original_phone_login }}">
                                    <input type="hidden" name="phone_pass" class="hidden" value="{{ $phone_pass }}">
                                    <input type="hidden" name="fronter" class="hidden" value="{{ $fronter }}">
                                    <input type="hidden" name="group_a" class="hidden" value="{{ $group_a }}">
                                    <input type="hidden" name="channel_group" class="hidden" value="{{ $channel_group }}">
                                    <input type="hidden" name="SQLdate" class="hidden" value="{{ $SQLdate }}">
                                    <input type="hidden" name="epoch" class="hidden" value="{{ $epoch }}">
                                    <input type="hidden" name="uniqueid" class="hidden" value="{{ $uniqueid }}">
                                    <input type="hidden" name="customer_zap_channel" class="hidden"
                                        value="{{ $customer_zap_channel }}">
                                    <input type="hidden" name="customer_server_ip" class="hidden"
                                        value="{{ $customer_server_ip }}">
                                    <input type="hidden" name="server_ip" id="server_ip" class="hidden" value="{{$server_ip}}">
                                    <input type="hidden" name="SIPexten" class="hidden" value="{{ $SIPexten }}">
                                    <input type="hidden" name="session_id" class="hidden" value="{{ $session_id }}">
                                    <input type="hidden" name="phone" class="hidden" value="{{ $phone }}">
                                    <input type="hidden" name="parked_by" class="hidden" value="{{ $parked_by }}">
                                    <input type="hidden" name="dispo" class="hidden" value="{{ $dispo }}">
                                    <input type="hidden" name="dialed_number" class="hidden" value="{{ $dialed_number }}">
                                    <input type="hidden" name="dialed_label" class="hidden" value="{{ $dialed_label }}">
                                    <input type="hidden" name="source_id" class="hidden" value="{{ $source_id }}">
                                    <input type="hidden" name="rank" class="hidden" value="{{ $rank }}">
                                    <input type="hidden" name="ownern" class="hidden" value="{{ $owner }}">
                                    <input type="hidden" name="camp_script" class="hidden" value="{{ $camp_script }}">
                                    <input type="hidden" name="in_script" class="hidden" value="{{ $in_script }}">
                                    <input type="hidden" name="in_script_two" class="hidden" value="{{ $in_script_two }}">
                                    <input type="hidden" name="script_width" class="hidden" value="{{ $script_width }}">
                                    <input type="hidden" name="script_height" class="hidden" value="{{ $script_height }}">
                                    <input type="hidden" name="agent_email" class="hidden" value="{{ $agent_email }}">
                                    <input type="hidden" name="user_custom_one" class="hidden" value="{{ $user_custom_one }}">
                                    <input type="hidden" name="user_custom_two" class="hidden" value="{{ $user_custom_two }}">
                                    <input type="hidden" name="user_custom_three" class="hidden"
                                        value="{{ $user_custom_three }}">
                                    <input type="hidden" name="user_custom_four" class="hidden" value="{{ $user_custom_four }}">
                                    <input type="hidden" name="user_custom_five" class="hidden" value="{{ $user_custom_five }}">
                                    <input type="hidden" name="preset_number_a" class="hidden" value="{{ $preset_number_a }}">
                                    <input type="hidden" name="preset_number_b" class="hidden" value="{{ $preset_number_b }}">
                                    <input type="hidden" name="preset_number_c" class="hidden" value="{{ $preset_number_c }}">
                                    <input type="hidden" name="preset_number_d" class="hidden" value="{{ $preset_number_d }}">
                                    <input type="hidden" name="preset_number_e" class="hidden" value="{{ $preset_number_e }}">
                                    <input type="hidden" name="preset_dtmf_a" class="hidden" value="{{ $preset_dtmf_a }}">
                                    <input type="hidden" name="preset_dtmf_b" class="hidden" value="{{ $preset_dtmf_b }}">
                                    <input type="hidden" name="did_id" class="hidden" value="{{ $did_id }}">
                                    <input type="hidden" name="did_extension" class="hidden" value="{{ $did_extension }}">
                                    <input type="hidden" name="did_pattern" class="hidden" value="{{ $did_pattern }}">
                                    <input type="hidden" name="did_description" class="hidden" value="{{ $did_description }}">
                                    <input type="hidden" name="closecallid" class="hidden" value="{{ $closecallid }}">
                                    <input type="hidden" name="xfercallid" class="hidden" value="{{ $xfercallid }}">
                                    <input type="hidden" name="agent_log_id" class="hidden" value="{{ $agent_log_id }}">
                                    <input type="hidden" name="entry_list_id" class="hidden" value="{{ $entry_list_id }}">
                                    <input type="hidden" name="call_id" class="hidden" value="{{ $call_id }}">
                                    <input type="hidden" name="user_group" class="hidden" value="{{ $user_group }}">
                                    <input type="hidden" name="list_name" class="hidden" value="{{ $list_name }}">
                                    <input type="hidden" name="list_description" class="hidden" value="{{ $list_description }}">
                                    <input type="hidden" name="entry_date" class="hidden" value="{{ $entry_date }}">
                                    <input type="hidden" name="did_custom_one" class="hidden" value="{{ $did_custom_one }}">
                                    <input type="hidden" name="did_custom_two" class="hidden" value="{{ $did_custom_two }}">
                                    <input type="hidden" name="did_custom_three" class="hidden" value="{{ $did_custom_three }}">
                                    <input type="hidden" name="did_custom_four" class="hidden" value="{{ $did_custom_four }}">
                                    <input type="hidden" name="did_custom_five" class="hidden" value="{{ $did_custom_five }}">
                                    <input type="hidden" name="called_count" class="hidden" value="{{ $called_count }}">
                                    <input type="hidden" name="email_row_id" class="hidden" value="{{ $email_row_id }}">
                                    <input type="hidden" name="LOGINvarONE" class="hidden" value="{{ $LOGINvarONE }}">
                                    <input type="hidden" name="LOGINvarTWO" class="hidden" value="{{ $LOGINvarTWO }}">
                                    <input type="hidden" name="LOGINvarTHREE" class="hidden" value="{{ $LOGINvarTHREE }}">
                                    <input type="hidden" name="LOGINvarFOUR" class="hidden" value="{{ $LOGINvarFOUR }}">
                                    <input type="hidden" name="LOGINvarFIVE" class="hidden" value="{{ $LOGINvarFIVE }}">
                                    <input type="hidden" name="hide_relogin_fields" class="hidden"
                                        value="{{ $hide_relogin_fields }}">
                                    <input type="hidden" name="web_vars" class="hidden" value="{{ $web_vars }}">
                                    <input type="hidden" name="session_name" class="hidden" value="{{ $session_name }}">


                                </div>
                            </form>
                        @else
                            <div class="alert alert-info" role="alert">
                                <h3>Please reopen the form.</h3>
                            </div>

                        @endif
                    </div>
                </div>
            </div>
        </div>



    @endsection

    <!-- container box ends here  -->

    <!-- <script>
        document.getElementById("lead-form").addEventListener("submit", function(event) {
            var ageSelect = document.getElementById("AGE");
            var smokerSelect = document.getElementById("Smoker");
            var closerSelect = document.getElementById("closer_name");

            if (ageSelect.value === "" || smokerSelect.value === "" || closerSelect.value === "") {
                alert("Please select all options before submitting the form.");
                event.preventDefault(); // Prevent form submission
            }
        });
    </script> -->






</body>

</html>